name: example
description: Interactively evaluate FHIRPath expressions
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fhir_plus: ^1.0.0
#   path: ../../fhir
  fhir_path_plus:
    path: ../../fhir_path
  google_fonts: ^8.0.2
  url_launcher: ^6.3.2
  yaml_writer: ^2.1.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  meta: ^1.18.2
